apiVersion: v1
kind: Service
metadata:
  name: wallet-app-backend
spec:
  type: NodePort
  selector:
    app: wallet-app-backend
  ports:
  - port: 3800
    nodePort: 30800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-app-backend
spec:
  selector:
    matchLabels:
      app: wallet-app-backend
  template:
    metadata:
      labels:
        app: wallet-app-backend
    spec:
      containers:
      - name: wallet-app-backend
        image: yosael/wallet-app-backend:1.0.0
        env:
          - name: POSTGRE_PASS
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          - name: POSTGRE_HOST
            value: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3800
