apiVersion: v1
kind: Service
metadata:
  name: wallet-app-web
spec:
  type: NodePort
  selector:
    app: wallet-app-web
  ports:
  - port: 80
    nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-app-web
spec:
  selector:
    matchLabels:
      app: wallet-app-web
  template:
    metadata:
      labels:
        app: wallet-app-web
    spec:
      containers:
      - name: wallet-app-web
        image: yosael/wallet-app-web:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
